# Generated by Django 5.2.1 on 2025-06-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_patient_identity_documents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdocument',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
